#pragma once

#define MASTER_LEFT
#define USE_SERIAL_PD2

#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
// #define TAPPING_FORCE_HOLD

#undef TAPPING_TERM
#define TAPPING_TERM 150
#define TAPPING_TERM_PER_KEY

#define UNICODE_SELECTED_MODES UC_MAC

#define COMBO_COUNT 3